export const products = [
  {
    id: 1,
    titulo: "BLANCA LA NIÑA QUE QUERIA VOLAR",
    autor: "Vicuña Benjamin",
    editorial: "PLANETA",
    precio: 7500,
    paginas: 200,
    peso: 400,
    formato: "Rústica",
    edicion: 2023,
    idioma: "Castellano",
    isbn: 9789504979050,
    resumen:
      "Este libro es un tributo a mi hija y una expresión desbordada y honesta de la experiencia que me tocó vivir. Una tragedia que me atravesó como un rayo y me dejó vacío. Me costó años asimilarla y de alguna manera sigo transitando el desierto, pero seguí viviendo.",
    img: "https://res.cloudinary.com/djiaogrh2/image/upload/v1685623742/Ebook/9789504979050_ekdjqs.jpg",
    genero: "Literatura",
    stock: 0,
  },
  {
    id: 2,
    titulo: "FORTUNA",
    autor: "Diaz Hernan",
    editorial: "ANAGRAMA",
    precio: 8250,
    paginas: 440,
    peso: 400,
    formato: "Rústica",
    edicion: 2023,
    idioma: "Castellano",
    isbn: 9788433901927,
    resumen:
      "En los triunfales años veinte, Benjamin Rask y su esposa Helen dominan Nueva York: él, un magnate financiero que ha amasado una fortuna; ella, la hija de unos excéntricos aristócratas. Pero a medida que la década se acerca a su fin, y sus excesos revelan un lado oscuro, a los Rask empiezan a rodearlos las sospechas… Ese es el punto de partida de Obligaciones, una exitosa novela de 1937 que todo Nueva York parece haber leído y que cuenta una historia que puede, sin embargo, contarse de algunas otras formas. Hernán Díaz compone en Fortuna un magistral puzle literario: una suma de voces, de versiones confrontadas que se complementan, se matizan y se contradicen, y, al hacerlo, ponen al lector ante las fronteras y los límites entre la realidad y la ficción, entre la verdad –acaso imposible de encontrar– y su versión manipulada. Fortuna explora los entresijos del capitalismo americano, el poder del dinero, las pasiones y las traiciones que mueven las relaciones personales y la ambición que todo lo malea.",
    img: "https://res.cloudinary.com/djiaogrh2/image/upload/v1685624357/Ebook/9788433901927_qi5uln.jpg",
    genero: "Literatura",
    stock: 6,
  },
  {
    id: 3,
    titulo: "ESTE DOLOR NO ES MIO",
    autor: "Wolynn Mark",
    editorial: "AGAIA EDICIONES",
    precio: 6800,
    paginas: 486,
    peso: 400,
    formato: "Rústica",
    edicion: 2018,
    idioma: "Castellano",
    isbn: 9788484456810,
    resumen:
      " DEPRESIÓN. ANSIEDAD. DOLORES CRÓNICOS. FOBIAS. PENSAMIENTOS OBSESIVOS. La evidencia científca muestra que los traumas pueden ser heredados. Existen pruebas fiables de que muchos problemas crónicos o de largo plazo pueden no tener su origen en nuestras vivencias inmediatas o en desequilibrios químicos de nuestro cerebro, sino en las vidas de nuestros padres, abuelos o bisabuelos. Mark Wolynn, fundador y director del Instituto de Constelaciones Familiares (FCI) y pionero en el estudio de los traumas familiares heredados, presenta en Este dolor no es mío un enfoque transformador que permite resolver problemas crónicos que no han podido ser aliviados mediante la terapia tradicional, los medicamentos u otras medidas.",
    img: "https://res.cloudinary.com/djiaogrh2/image/upload/v1685636454/Ebook/9788484456810_obj6i3.jpg",
    genero: "Salud",
    stock: 5,
  },
  {
    id: 4,
    titulo: "EL AMOR ES IMPOSIBLE",
    autor: "Sztajnszrajber Dario",
    editorial: "AGAIA PAIDOS",
    precio: 6500,
    paginas: 416,
    peso: 400,
    formato: "Rústica",
    edicion: 2023,
    idioma: "Castellano",
    isbn: 9789501204070,
    resumen:
      " Qué significa que el único amor verdadero sea el amor imposible? ¿Es el amor lo que suponemos que es? O antes que eso, ¿es lo imposible aquello definido como lo inalcanzable, lo inconsumable, lo inenarrable? ¿Y si fueran las preguntas lo que hay que cambiar porque es en la imposibilidad del encuentro amoroso donde radica su verdad? Este libro es una propuesta de deconstrucción radical sobre uno de los eventos más radicales de nuestra existencia. Ocho tesis que tienen el arrojo de devenir en una serie de desvelos, nuevas intuiciones, destellos que nos inviten a temblar. Es la puesta en página de una práctica política concreta, que increpa a ese amor comercial, romántico, que se nos vende como domi-nante, como único y normativo. Es ir a martillazos contra esa arquitectura sentimental sostenida por el sentido común, por definiciones y naturalezas forzadas. Y entonces, sí: categorías cristalizadas como la pareja, la familia, la media naranja y el primer amor, entre otras, son puestas en evidencia, caen bajo su propio peso: se rompen. El amor es imposible conduce al insomnio, y de ahí a una revolución íntima y perturbadora comandada por el deseo genuino de la intranquilidad: no queremos estar en donde estamos. Un trabajo de años, de lecturas y de diálogos en el que Darío Sztajnszrajber pone una vez más, al alcance de quienes estén dispuestos a jugar el juego, las herramientas de la filosofía para desandar lo andado, rebelarse y exigir siempre, aunque suene a destiempo y desubicado, animarse a lo imposible.",
    img: "https://res.cloudinary.com/djiaogrh2/image/upload/v1685636454/Ebook/9789501204070_ka9u0h.jpg",
    genero: "Sociales",
    stock: 3,
  },
  {
    id: 5,
    titulo: "SARMIENTO",
    autor: "Balmaceda Daniel Dario",
    editorial: "SUDAMERICANA",
    precio: 5999,
    paginas: 408,
    peso: 460,
    formato: "Rústica",
    edicion: 2023,
    idioma: "Castellano",
    isbn: 9789500768757,
    resumen:
      " Sarmiento renunció a la masonería antes de asumir, vivió de prestado en casas de parientes y sufrió un grave atentado por parte del mismo bando que propició el asesinato de Urquiza. Cargó con la epidemia de la fiebre amarilla y la mayor tragedia naval de su tiempo. Completó su mandato en medio de una rebelión militar. Lo trataron de borracho, corrupto, inútil y anticonstitucional. Pero el contexto hostil no le impidió expandir los ferrocarriles y el telégrafo, promover la ciencia y la tecnología, impulsar el uso de maquinaria agrícola, concretar el primer censo y fomentar el crecimiento de las economías regionales. Aunque algo arrogante, altanero y soberbio, su inteligencia le permitió adoptar lo mejor del modelo norteamericano que tanto admiraba. Las cartas íntimas a su mujer, amantes y amigos, sus peleas con las maestras norteamericanas, la cuestionada visión del gaucho, la polémica por la supuesta entrega de la Patagonia y el mito de la Casa Rosada son solo algunas de las originales historias que pintan un perfil amplio, a veces ignorado y, sobre todo, cautivador, del presidente que torció el rumbo del país.",
    img: "https://res.cloudinary.com/djiaogrh2/image/upload/v1685636454/Ebook/9789500768757_rlhqcv.jpg",
    genero: "Sociales",
    stock: 8,
  },
  {
    id: 6,
    titulo: "LA GIOCONDA Y LEONARDOIENTO",
    autor: "Lopez Rosetti Daniel",
    editorial: "PLANETA",
    precio: 5700,
    paginas: 288,
    peso: 400,
    formato: "Rústica",
    edicion: 2023,
    idioma: "Castellano",
    isbn: 9789504980889,
    resumen:
      " Leonardo da Vinci (1452-1519), uno de los seres humanos mas brillantes que haya existido, es el paradigma del genio renacentista. Impresionado por la combinacion magnifica entre su creatividad artistica y su capacidad cientifica, Daniel Lopez Rosetti le dedica, desde hace mas de veinte aos, horas de estudio e investigacion. Tras la comprension neurocientifica del porque del genio y la creatividad, en un giro ficcional, el autor le da voz a la Gioconda, la protagonista de la obra mas emblematica de Da Vinci. Consustanciada con su creador desde la primera pincelada, es la encargada de develar los antecedentes biograficos de Leonardo y las particularidades historicas y culturales de la epoca. La Gioconda, que lo acompao hasta sus ultimos dias den el castillo de Clos-Luce, Francia, cobra vida y, desde su mirada privilegiada, muestra los rasgos intimos que caracterizaron a esta personalidad extraordinaria y compleja, que revoluciono la historia del arte y se adelanto con sus estudios anatomicos a muchas conclusiones posteriores de la medicina. Una vez mas, Daniel Lopez Rosetti brinda una trama elocuentey apasionante, rica en informaciones y detalles, de lo que puede alcanzar la singularidad del ser humano.",
    img: "https://res.cloudinary.com/djiaogrh2/image/upload/v1685636454/Ebook/9789504980889_nnsqya.jpg",
    genero: "Salud",
    stock: 4,
  },
  {
    id: 7,
    titulo: "APIA DE ROMA",
    autor: "Rivero Viviana",
    editorial: "PLANETA",
    precio: 8900,
    paginas: 640,
    peso: 400,
    formato: "Rústica",
    edicion: 2023,
    idioma: "Castellano",
    isbn: 9789504981107,
    resumen:
      " Apia Pópulus está a punto de perder a su madre. A pesar de su corta edad, conforme a las costumbres imperantes, contrae matrimonio con Salvio Sextus, un próspero comerciante de perlas de edad avanzada. En el Palatino, el barrio más encumbrado de la ciudad, la joven debe revestirse con una coraza para enfrentar la vida con alguien a quien no ama, cumplir con sus obligaciones de ama y defender su casa de las confabulaciones políticas. Roma es un hervidero repleto de intrigas. Tras el asesinato de Julio César en el Senado, Marco Antonio y Octavio, el futuro emperador, se disputan el poder. Los crímenes están a la orden del día y Salvio Sextus teme por su vida. Apia soporta con estoicismo la tiranía de su esposo y el ataque constante de Senecio, el hijo de éste. Como si fuera poco, se ve forzada a aceptar los humillantes juegos de dominación a los que, en su condición de mujer, la somete uno de los poderosos de la ciudad. Su único apoyo es su fiel esclava Furnilla. Juntas forjarán una alianza inquebrantable y lucharán por abrirse camino en un medio hostil. Hasta que la aparición de Manius Marcio, un atractivo centurión, trastoca la vida de Apia y le permite descubrir sentimientos y sensaciones que jamás había experimentado. A partir de ese momento tendrá que hacer equilibrio entre dar rienda suelta a su apasionado romance y pelear su lugar en un mundo de negocios patriarcal y misógino. Narrada en dos tiempos, esta novela relata una historia de pasión, violencia y superación en pleno apogeo del Imperio Romano. Con su habitual maestría para construir tramas apasionantes, Viviana Rivero retrata a una mujer que hace frente a los mandatos y las imposiciones de su época en pos de la igualdad, la independencia y el amor verdadero.",
    img: "https://res.cloudinary.com/djiaogrh2/image/upload/v1685636454/Ebook/9789504981107_y8vwmv.jpg",
    genero: "Literatura",
    stock: 6,
  },
  {
    id: 8,
    titulo: "HABITOS ATOMICOS",
    autor: "Clear James",
    editorial: "PAIDOS",
    precio: 8200,
    paginas: 328,
    peso: 400,
    formato: "Rústica",
    edicion: 2019,
    idioma: "Castellano",
    isbn: 9789501298321,
    resumen:
      " HÁBITOS ATÓMICOS parte de una simple pero poderosa pregunta: ¿Cómo podemos vivir mejor? Sabemos que unos buenos hábitos nos permiten mejorar significativamente nuestra vida, pero con frecuencia nos desviamos del camino: dejamos de hacer ejercicio, comemos mal, dormimos poco, despilfarramos. ¿Por qué es tan fácil caer en los malos hábitos y tan complicado seguir los buenos? James Clear nos brinda fantásticas ideas basadas en investigaciones científicas, que le permiten revelarnos cómo podemos transformar pequeños hábitos cotidianos para cambiar nuestra vida y mejorarla. Esta guía pone al descubierto las fuerzas ocultas que moldean nuestro comportamiento -desde nuestra mentalidad, pasando por el ambiente y hasta la genética- y nos demuestra cómo aplicar cada cambio a nuestra vida y a nuestro trabajo. Después de leer este libro, tendrás un método sencillo para desarrollar un sistema eficaz que te conducirá al éxito.",
    img: "https://res.cloudinary.com/djiaogrh2/image/upload/v1685636454/Ebook/9789501298321_xlvlhu.jpg",
    genero: "Salud",
    stock: 7,
  },
  {
    id: 9,
    titulo: "V13",
    autor: "Carrere Emmanuel",
    editorial: "ANAGRAMA",
    precio: 5750,
    paginas: 272,
    peso: 400,
    formato: "Rústica",
    edicion: 2019,
    idioma: "Castellano",
    isbn: 9788433904973,
    resumen:
      " La crónica, descarnada y humana, del proceso judicial por el atentado islamista contra la sala Bataclan. V13: viernes 13 de noviembre de 2015. En tres puntos diferentes de París se producen atentados yihadistas. El más grave es el de la sala Bataclan, donde están actuando los Eagles of Death Metal. El resultado de los ataques en el corazón de Francia es de ciento treinta muertos y más de cuatrocientos heridos. Años después, durante nueve meses ?entre septiembre de 2021 y junio de 2022?, se celebra el juicio en el Palacio de Justicia de la capital. Hay catorce acusados: el principal es el único superviviente de entre los terroristas de Estado Islámico que participaron en la masacre. Sobrevivió porque no detonó su cinturón con explosivos. ¿Falló el mecanismo? ¿Tuvo miedo? ¿O quizá un fugaz momento de arrepentimiento y humanidad? El resto son colaboradores en distintos grados. Y además están los testigos ?que cuentan historias de una gran crudeza?, los familiares de los fallecidos, los severos fiscales, los abogados defensores, que utilizan argucias para tratar de salvar a sus clientes, el tribunal, que debe emitir sentencia? La justicia evalúa con frialdad la barbarie. Emmanuel Carr ¿re cubre el juicio y envía sus crónicas semanales aáL?Obs. Esos textos son la base de este libro. En sus páginas encontramos la narración del juicio, la voz de las víctimas, los advenedizos que han tratado de hacerse pasar por víctimas, los héroes que ayudaron a detener a los criminales, los corrillos de los abogados, los detalles entre bambalinas? La dimensión humana y la dimensión política. El resultado: un volumen sobrecogedor y un testimonio necesario. El periodismo hecho literatura a través de la perspicaz mirada de Carrere.",
    img: "https://res.cloudinary.com/djiaogrh2/image/upload/v1685636454/Ebook/9788433904973_hlax5y.jpg",
    genero: "Literatura",
    stock: 5,
  },
  {
    id: 10,
    titulo: "CONOCER A PERON",
    autor: "Abal Medina Juan Manuel",
    editorial: "PLANETA",
    precio: 8700,
    paginas: 400,
    peso: 400,
    formato: "Rústica",
    edicion: 2022,
    idioma: "Castellano",
    isbn: 9789504978251,
    resumen:
      "Juan Manuel Abal Medina fue, a los veintisiete años, el hombre elegido por Peron para construir la estrategia de su retorno en noviembre de 1972, luego de diecisiete años de destierro. Formado en el nacionalismo católico, hermano de Fernando -fundador de Montoneros, al que acababan de matar-, peronista recién llegado al Movimiento, Abal Medina recorrió el laberinto de cada uno de los sectores en pugna para traer a Peron al país, cuando la violencia ya golpeaba desde el subsuelo del peronismo. Con una prosa emotiva y por momentos devastadora, quien fue el último reten para impedir el enfrentamiento relata como se fue urdiendo la compleja trama de los hechos, cuyas esquirlas se derramarían durante la década de 1970 y que aún hoy, medio siglo después, siguen conmoviendo. Ls conversaciones secretas de su hermano con el escritor Leopoldo Marechal, determinantes para el secuestro y muerte del general Aramburu, el conflicto jamás revelado entre Campora y Peron sobre la presidencia, los pormenores de la tragedia anunciada de Ezeiza, las negociaciones secretas entre metalúrgicos y montoneros para frenar la dinámica del conflicto, el crimen sin retorno de Jose Ignacio Rucci, y la entronización de Jose Lopez Rega e Isabel en el poder doméstico son parte de una pintura vibrante, desoladora y arida que atraviesan estas memorias que Abal Medina vuelca por primera vez en un libro. Mas que un relato sobre los años 70 y peronismo, Conocer á Peron es la visión lúcida de un testigo y protagonista privilegiado que vió y alertó sobre el drama inminente, mientras se acababa el diálogo y se velaban las armas.",
    img: "https://res.cloudinary.com/djiaogrh2/image/upload/v1685636455/Ebook/9789504978251_dhm9rc.jpg",
    genero: "Sociales",
    stock: 4,
  },
  {
    id: 11,
    titulo: "EL PODER DE LAS PALABRAS",
    autor: "Sigman Mariano",
    editorial: "DEBATE",
    precio: 6699,
    paginas: 352,
    peso: 400,
    formato: "Rústica",
    edicion: 2022,
    idioma: "Castellano",
    isbn: 9789877950465,
    resumen:
      "Nuestra mente es mucho más maleable de lo que creemos y, a pesar de que conservamos toda la vida la misma capacidad de aprender que tenemos de chicos, con el tiempo vamos perdiendo la necesidad y la motivación para hacerlo. Así, empezamos a convencernos de lo que no podemos: o somos malos para la matemática, o no nacimos para la música, o no podemos manejar nuestra ira, o nos es imposible superar el miedo. Este libro sostiene y demuestra que, independientemente del momento de nuestra existencia que atravesemos, podemos demoler esas creencias y cambiar ideas y sentimientos, aun aquellos más profundamente arraigados, aprendiendo a conversar. En efecto, la conversación -con otros y con nosotros- es la herramienta más extraordinaria para transformar nuestra vida. Después del éxito mundial de La vida secreta de la mente, Mariano Sigman reúne los avances más recientes de la neurociencia y los combina con historias de vida y una dosis importante de humor para explicar cómo y por qué las buenas conversaciones mejoran nuestras decisiones, ideas, memoria y emociones. He aquí un poder que está a nuestro alcance y podemos emplear para cambiar nuestra mente y tener una vida mejor: el poder de las palabras.",
    img: "https://res.cloudinary.com/djiaogrh2/image/upload/v1685636454/Ebook/9789877950465_jvmfei.jpg",
    genero: "Salud",
    stock: 2,
  },
  {
    id: 12,
    titulo: "LAS AVENTURAS DE LYNA Y DANI : ELIGE TU HISTORIA",
    autor: "Vallejos Lyna",
    editorial: "ALTEA",
    precio: 2499,
    paginas: 56,
    peso: 110,
    formato: "Rústica",
    edicion: 2023,
    idioma: "Castellano",
    isbn: 9789877364026,
    resumen:
      "Ahora podrás acompañar a Lyna, Dani, Meli, la abuela Rita y las mascotas en sus locas aventuras y decidir cuál será el recorrido y qué sucederá. íVos elegís cómo será la historia! Disfrutarás de horas de diversión, y cuando llegues al final, podrás retroceder para volver a empezar por otro camino. íNo esperes más para meterte en estas páginas y viajar junto a tus personajes favoritos!",
    img: "https://res.cloudinary.com/djiaogrh2/image/upload/v1685636454/Ebook/9789877364026_mpducq.jpg",
    genero: "Literatura",
    stock: 7,
  },
  {
    id: 13,
    titulo: "DIBU MARTINEZ : PASION POR EL FUTBOL",
    autor: "Martinez Emiliano",
    editorial: "MONTENA",
    precio: 3499,
    paginas: 112,
    peso: 160,
    formato: "Rústica",
    edicion: 2022,
    idioma: "Castellano",
    isbn: 9789878940182,
    resumen:
      "El fútbol es su gran pasión, eso Dibu Martinez lo sabe desde que era muy chico. En la playa con su hermano y los Mostris, el fútbol era cosa de todos los días. La preparación y el compromiso fueron siempre sus guías. ¿Cómo se llega a ser uno de los mejores arqueros del mundo? ¿Cómo se persiguen los sueños? Siempre para adelante, siempre poniendo garra y esforzándose. íY que la pasión te lleve a la gloria! «Emi logró transitar un camino exitoso. Tuvo obstáculos, pero los fue atravesando con paciencia y grandeza. La pasión y la determinación lo llevaron a donde está hoy y por eso es un gran ejemplo para todos». Pepe Santoro",
    img: "https://res.cloudinary.com/djiaogrh2/image/upload/v1685636455/Ebook/9789878940182_ogi9yd.jpg",
    genero: "Literatura",
    stock: 9,
  },
  {
    id: 14,
    titulo: "EL NUDO",
    autor: "Pagni Carlos",
    editorial: "PLANETA",
    precio: 9800,
    paginas: 776,
    peso: 400,
    formato: "Rústica",
    edicion: 2023,
    idioma: "Castellano",
    isbn: 9789504981015,
    resumen:
      "Un territorio, el conurbano bonaerense, y una fecha concreta, la crisis de 2001, son, además de los protagonistas de este libro, las coordenadas que terminaron con un modelo de país y forjaron la Argentina que llega hasta el presente, la de una crisis sin final, con la degradación de la vida material como telón de fondo permanente y al parecer inevitable. El modelo económico que había entrado en convulsión estalló en el lugar donde se lo había fundado. El conurbano de la provincia de Buenos Aires, dice Carlos Pagni en el comienzo de estas páginas, que son el resultado de una indagación de cinco años. En la extraordinaria auscultación de ese temblor que supone El nudo, Pagni cruza sus dos juegos de herramientas: las del analista político mejor informado de la Argentina y las del historiador. Del mismo modo, aquí conviven dos libros: los grandes temas que caracterizan al conurbano (pobreza, clientelismo, hacinamiento, cuentapropismo, informalidad y fallas crónicas del Estado) y la historia de la conformación de ese territorio indómito, los hitos de la irrupción de la provincia de Buenos Aires en la política nacional, desde finales del siglo XIX hasta un tour de force final con el relato de 2001, porque, como dice el autor, la sociedad sigue atrapada en una agenda de problemas que se inauguraron en medio de esa gran alteración.",
    img: "https://res.cloudinary.com/djiaogrh2/image/upload/v1685636455/Ebook/9789504981015_g4gaki.jpg",
    genero: "Sociales",
    stock: 1,
  },
  {
    id: 15,
    titulo: "EL HOMBRE EN BUSCA DE SENTIDO",
    autor: "Frankl Viktor E.",
    editorial: "HERDER",
    precio: 3490,
    paginas: 160,
    peso: 210,
    formato: "Rústica",
    edicion: 2016,
    idioma: "Castellano",
    isbn: 9788425432026,
    resumen:
      "El doctor Frankl, psiquiatra y escritor, suele preguntar a sus pacientes aquejados de múltiples padecimientos: «¿Por qué no se suicida usted?» Y muchas veces, de las respuestas extrae una orientación para la psicoterapia a aplicar: a éste, lo que le ata a la vida son los hijos; al otro, un talento, una habilidad sin explotar; a un tercero, quizás, sólo unos cuantos recuerdos que merece la pena rescatar del olvido. Tejer estas tenues hebras de vidas rotas en una urdimbre firme, coherente, significativa y responsable es el objeto con que se enfrenta la logoterapia. En esta obra, Viktor E. Frankl explica la experiencia que le llevó al descubrimiento de la logoterapia. Prisionero, durante mucho tiempo, en los desalmados campos de concentración, él mismo sintió en su propio ser lo que significaba una existencia desnuda. ¿Cómo pudo él que todo lo había perdido, que había visto destruir todo lo que valía la pena, que padeció hambre, frío, brutalidades sin fin, que tantas veces estuvo a punto del exterminio, cómo pudo aceptar que la vida fuera digna de vivirla? El psiquiatra que personalmente ha tenido que enfrentarse a tales rigores merece que se le escuche, pues nadie como él para juzgar nuestra condición humana sabia y compasivamente. Las palabras del doctor Frankl alcanzan un temple sorprendentemente esperanzador sobre la capacidad humana de trascender sus dificultades y descubrir la verdad.",
    img: "https://res.cloudinary.com/djiaogrh2/image/upload/v1685636454/Ebook/9788425432026_lqziwp.jpg",
    genero: "Sociales",
    stock: 8,
  },
];
